testing errors

diff --git a/.github/workflows/validate-links.yml b/.github/workflows/validate-links.yml
--- a/.github/workflows/validate-links.yml
+++ b/.github/workflows/validate-links.yml
@@ -30,7 +30,7 @@ jobs:
         run: node ./scripts/validate-links.js
 
       - name: Post results as PR comment
-        if: always()
+        if: failure()
         uses: actions/github-script@v7
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -47,5 +47,9 @@ jobs:
             await github.rest.issues.createComment({
               ...context.repo,
               issue_number: pullRequestNumber,
-              body: result.includes('Invalid Links:') ? `## ❌ Link Validation Failed\n\`\`\`\n${result}\n\`\`\`` : `## ✅ Link Validation Passed\n\`\`\`\n${result}\n\`\`\``
+              body: `## ❌ Link Validation Failed\n\`\`\`\n${result}\n\`\`\``
             });
+
+      - name: Fail the job if duplicates are found
+        if: failure()
+        run: exit 1
